### ISSUE TITLE
Output to ttl or owl fails with `pubmed-annotate`

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#139]
Trying to get output in ttl or owl format for pubmed-annotate fails with a few different errors.
Running something like the following:
```
ontogpt -vvv pubmed-annotate -t ibd_literature "irritable bowel disease drug blood" -o output.owl -O owl
```
initially throws an AttributeError because the `write_extraction` method in cli.py expects owl and ttl output to pass `knowledge_engine.schemaview` to the exporter.
So, as a quick fix for that (thanks @hrshdhgd), ensure that calls to `write_extraction` include the knowledge engine (usually `ke`).

_however,_

there's still potential to not get the desired output, as seen below:
```
$ ontogpt -vvv pubmed-annotate -t ibd_literature "irritable bowel disease drug blood" -o output.owl -O owl
...
INFO:root:{'genes': ['Not specified in the text'], 'exposures': ['CHEBI:16243'], 'gene_exposures_relationships': []}
DEBUG:root:BASE=/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema
INFO:root:Default_range not specified. Default set to 'string'
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 301, in pubmed_annotate
    write_extraction(results, output, output_format, ke)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 102, in write_extraction
    exporter.export(results, output, knowledge_engine.schemaview)
  File "/home/harry/ontogpt/src/ontogpt/io/owl_exporter.py", line 43, in export
    ne_as_dc = self._as_dataclass_object(named_entity, schemaview)
  File "/home/harry/ontogpt/src/ontogpt/io/owl_exporter.py", line 55, in _as_dataclass_object
    dataclasses_module = PythonGenerator(schemaview.schema).compile_module()
  File "<string>", line 27, in __init__
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/generators/pythongen.py", line 57, in __post_init__
    super().__post_init__()
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/generator.py", line 189, in __post_init__
    self._initialize_using_schemaloader(schema)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/generator.py", line 232, in _initialize_using_schemaloader
    loader.resolve()
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/schemaloader.py", line 252, in resolve
    self.raise_value_error(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/schemaloader.py", line 1037, in raise_value_error
    SchemaLoader.raise_value_errors(error, loc_str)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/schemaloader.py", line 1047, in raise_value_errors
    raise ValueError(f'{TypedNode.yaml_loc(loc_str, suffix="")} {error}')
ValueError: File "<file>", line 255, col 16 slot: geneExposureRelationship__molecular_activity - unrecognized range (Exposure)
```

OK, so this looks like an issue with the schema but why do we see it now and not with yaml output?

Trying with a different template raises its own issues:
```
$ontogpt -vvv pubmed-annotate -t ctd.ChemicalToDiseaseRelationship "irritable bowel disease drug blood" -o output.owl -O owl
...
ERROR:root:Line 'No entities were provided in the given text.' does not contain a colon; ignoring
DEBUG:root:RAW: None
DEBUG:root:Grounding annotation object None
ERROR:root:Cannot ground None annotation, cls=ChemicalToDiseaseRelationship
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 301, in pubmed_annotate
    write_extraction(results, output, output_format, ke)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 102, in write_extraction
    exporter.export(results, output, knowledge_engine.schemaview)
  File "/home/harry/ontogpt/src/ontogpt/io/owl_exporter.py", line 31, in export
    id_slot = schemaview.get_identifier_slot(cls_name)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 1331, in get_identifier_slot
    for sn in self.class_slots(cn, imports=imports):
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 1150, in class_slots
    ancs = self.class_ancestors(class_name, imports=imports)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 703, in class_ancestors
    return _closure(lambda x: self.class_parents(x, imports=imports, mixins=mixins, is_a=is_a),
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 56, in _closure
    vals = f(i)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 703, in <lambda>
    return _closure(lambda x: self.class_parents(x, imports=imports, mixins=mixins, is_a=is_a),
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 590, in class_parents
    cls = self.get_class(class_name, imports, strict=True)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 507, in get_class
    raise ValueError(f'No such class as "{class_name}"')
ValueError: No such class as "NoneType"
```

**Comment by caufieldjh** [comment]
So the real issue here is that problems with the underlying schema template should be reported as such, even if the issue they're causing is a failure to write to the desired output format.

**Comment by caufieldjh** [comment]
The `No such class as "NoneType"` error isn't really a problem with a schema, though - it's a problem with the call to `schemaview.get_identifier_slot(cls_name)` passing None (I think?)

**Comment by hrshdhgd** [comment]
I tried running this locally and I get this as the owl output (without errors):
```
Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label CHEBI:16243 "Quercetin" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label HGNC:7153 "MMD" )
    AnnotationAssertion( rdfs:label HGNC:1693 "CD68" )
    AnnotationAssertion( rdfs:label HGNC:11892 "TNF" )
    AnnotationAssertion( rdfs:label HGNC:5992 "IL1B" )
    AnnotationAssertion( rdfs:label HGNC:6018 "IL6" )
    AnnotationAssertion( rdfs:label HGNC:6025 "CXCL8" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label CHEBI:15366 "acetic acid" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label CHEBI:50904 "environmental proteins (allergens), histamine, leukotrienes, food allergens" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label HGNC:11059 "xCT" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label HGNC:12680 "VEGF" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label HGNC:11142 "SIK1" )
    AnnotationAssertion( rdfs:label HGNC:21680 "SIK2" )
    AnnotationAssertion( rdfs:label HGNC:5962 "IL-10" )
    AnnotationAssertion( rdfs:label HGNC:3796 "c-FOS" )
    AnnotationAssertion( rdfs:label HGNC:11930 "LIGHT" )
    AnnotationAssertion( rdfs:label HGNC:11240 "SPHK1" )
    AnnotationAssertion( rdfs:label HGNC:26148 "CRTC3" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label CHEBI:50858 "corticosteroids" )
    AnnotationAssertion( rdfs:label CHEBI:46195 "acetaminophen" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature> )Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label CHEBI:27300 "vitamin D" )
)Prefix( owl: = <http://www.w3.org/2002/07/owl#> )
Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )
Prefix( rdfs: = <http://www.w3.org/2000/01/rdf-schema#> )
Prefix( xsd: = <http://www.w3.org/2001/XMLSchema#> )
Prefix( xml: = <http://www.w3.org/XML/1998/namespace> )
Prefix( linkml: = <https://w3id.org/linkml/> )
Prefix( core: = <http://w3id.org/ontogpt/core/> )
Prefix( NCIT: = <http://purl.obolibrary.org/obo/NCIT_> )
Prefix( RO: = <http://purl.obolibrary.org/obo/RO_> )
Prefix( shex: = <http://www.w3.org/ns/shex#> )
Prefix( schema: = <http://schema.org/> )

Ontology( <http://w3id.org/ontogpt/ibd_literature>
    AnnotationAssertion( rdfs:label CHEBI:16243 "quercetin" )
)
```

Is this what you were expecting?

**Comment by caufieldjh** [comment]
Yes! Hrm, maybe a newer version of linkml-runtime will help - nope, after updating that to 1.5.4 I still get 
```
ValueError: No such class as "NoneType"
```
for a particular document. Could just be an edge case that doesn't appear in every set of text completions

**Comment by caufieldjh** [comment]
I've narrowed this down to be cases where there isn't a parsed object in the GPT text completion, so you get something like 
```
ERROR:root:Line 'No entities were provided in the given text.' does not contain a colon; ignoring
```
and in turn, an annotation object of None. This None gets parsed without errors by some writers, like the YAML dumper, but not by others.
