### ISSUE TITLE
About ModuleNotFoundError: No module named 'importlib.util' issue

### ISSUE THREAD

**Issue by yy20716** [monarch-initiative/ontogpt#18]
Hello @cmungall, I was trying to install and test ontogpt but I was not able to proceed further because of the importlib issue shown below. It seems that it keeps searching for the python library called importlib, but most people say that library is already available in Python 3.9. 

```
yy20716@yy20716-VirtualBox:~/ontogpt-test$ python3.9 -m venv venv
yy20716@yy20716-VirtualBox:~/ontogpt-test$ source venv/bin/activate
(venv) yy20716@yy20716-VirtualBox:~/ontogpt-test$ export PYTHONPATH=.:$PYTHONPATH
(venv) yy20716@yy20716-VirtualBox:~/ontogpt-test$ pip install ontogpt
Collecting ontogpt
  Downloading ontogpt-0.2.0-py3-none-any.whl (978 kB)
     |████████████████████████████████| 978 kB 4.0 MB/s 
Collecting bioc<3.0,>=2.0.post5
  Downloading bioc-2.0.post5-py3-none-any.whl (37 kB)
Collecting gilda<0.11.0,>=0.10.3
  Downloading gilda-0.10.3-py3-none-any.whl (166 kB)
     |████████████████████████████████| 166 kB 14.7 MB/s 
Collecting oaklib<0.2.0,>=0.1.64
  Downloading oaklib-0.1.73-py3-none-any.whl (458 kB)
     |████████████████████████████████| 458 kB 14.9 MB/s 
Collecting linkml-owl<0.3.0,>=0.2.7
  Downloading linkml_owl-0.2.7-py3-none-any.whl (16 kB)
Collecting airium<0.3.0,>=0.2.5
  Downloading airium-0.2.5-py3-none-any.whl (13 kB)
Collecting nlpcloud<2.0.0,>=1.0.39
  Downloading nlpcloud-1.0.40-py3-none-any.whl (4.5 kB)
Collecting importlib<2.0.0,>=1.0.4
  Downloading importlib-1.0.4.zip (7.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/yy20716/ontogpt-test/venv/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m29z69lc/importlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m29z69lc/importlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-m29z69lc/importlib/pip-egg-info
         cwd: /tmp/pip-install-m29z69lc/importlib/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/yy20716/ontogpt-test/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/usr/lib/python3.9/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/lib/python3.9/distutils/dist.py", line 19, in <module>
        from distutils.util import check_environ, strtobool, rfc822_escape
      File "/usr/lib/python3.9/distutils/util.py", line 9, in <module>
        import importlib.util
    ModuleNotFoundError: No module named 'importlib.util'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I also see similar errors when trying to use poetry: 
```
(venv) yy20716@yy20716-VirtualBox:~/ontogpt$ poetry install
Installing dependencies from lock file

Package operations: 18 installs, 1 update, 0 removals

  • Installing adeft (0.11.2)
  • Installing bioc (2.0.post5)
  • Installing eutils (0.6.0)
  • Installing importlib (1.0.4): Failed

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with importlib (1.0.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "importlib (==1.0.4)"'.

```
I tested this issue using other ubuntu machines, but the same issue also arises. Can you help me to solve or avoid this issue? Thank you.

p.s. I tried with the version 1.1, and the same issue still exists. I wonder if we could remove this importlib in the dependencies.

**Comment by caufieldjh** [comment]
Fixed by #122 

@yy20716 please feel free to reopen if this importlib issue is still happening.
