### ISSUE TITLE
`embed` command fails with `sqlite3.InterfaceError`

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#184]
The `embed` command fails as follows:

```
$ ontogpt -vvv embed "test"
INFO:root:Logger root set to level 10
INFO:root:API KEY path = /home/harry/.config/ontology-access-kit/openai-apikey.txt
INFO:ontogpt.clients.openai_client:Caching OpenAI responses to /home/harry/ontogpt/.openai_cache.db
INFO:ontogpt.clients.openai_client:creating embeddings cache
INFO:ontogpt.clients.openai_client:Embeddings cache table already exists
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 1028, in embed
    resp = client.embeddings(text)
  File "/home/harry/ontogpt/src/ontogpt/clients/openai_client.py", line 155, in embeddings
    res = cur.execute(
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```

This happens with a freshly created `.openai_cache.db`, too.

**Comment by caufieldjh** [comment]
For some reason the `text` object is entering `embeddings()` as a tuple, not a str.

Also noticed the default model for embeddings is set as `text-embedding-ada-002`, and that's not what we want. Different issue.
