### ISSUE TITLE
TypeError: ConfiguredBaseModel.__init_subclass__() takes no keyword arguments

### ISSUE THREAD

**Issue by kluo9** [monarch-initiative/ontogpt#188]
Hello,

After compile the schema I tried 

ontogpt extract -t myschema -i mytext.txt

and got the following error:

Traceback (most recent call last):
  File "/opt/conda/bin/ontogpt", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/cli.py", line 290, in extract
    ke = SPIRESEngine(template, **kwargs)
  File "<string>", line 23, in __init__
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/engines/knowledge_engine.py", line 155, in __post_init__
    self.template_class = self._get_template_class(self.template)
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/engines/knowledge_engine.py", line 247, in _get_template_class
    mod = importlib.import_module(f"ontogpt.templates.{module_name}")
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/templates/traffic.py", line 19, in <module>
    class ConfiguredBaseModel(WeakRefShimBaseModel,
  File "/opt/conda/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 123, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.9/abc.py", line 106, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: ConfiguredBaseModel.__init_subclass__() takes no keyword arguments

Do you know what is wrong?

Thanks!

**Comment by caufieldjh** [comment]
Hi @kluo9, thanks for your issue.
I believe this happens when the Python classes generated from the yaml template aren't compatible with the newest version of the Pydantic module. There's a quick way to verify this - take a look at the top of your `myschema.py` and if you find this line:
```
from pydantic import BaseModel as BaseModel
```
then that's the issue.
Try changing it to be
```
from pydantic.v1 import BaseModel as BaseModel
```
and try your extract command again.

That's just a workaround, though - it looks like this is actually a bug, as the generated Python should include the correct import but currently does not. A fix is incoming.

**Comment by kluo9** [comment]
Thanks @caufieldjh for the quick reply! Yes changing the Pydantic version works.

**Comment by serenalotreck** [comment]
Hi @caufieldjh -- I'm currently getting this same error, but when just running `ontogpt --help`. I'm running Python 3.10.12, and I just installed both ontogpt and oaklib with pip. Wondering if this fix was pushed with the version that's currently available on pip?

Thanks!

**Comment by caufieldjh** [comment]
Hi @serenalotreck - yes, this error should be fixed in ontogpt v0.3.3, but there's still the possibility that it's trying to use an incompatible version of pydantic (oaklib doesn't care about the pydantic version, but ontogpt needs pydantic >v2). 
Does it fix your error to specifically install `pydantic==2.3.0`?

**Comment by serenalotreck** [comment]
After installation, I get a different error when I run `ontogpt --help`:

```
Traceback (most recent call last):
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/bin/ontogpt", line 5, in <module>
    from ontogpt.cli import main
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/ontogpt/cli.py", line 34, in <module>
    from ontogpt.engines.gpt4all_engine import GPT4AllEngine  # type: ignore
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/ontogpt/engines/gpt4all_engine.py", line 34, in <module>
    from ontogpt.utils.gpt4all_runner import chain_gpt4all_model, set_up_gpt4all_model
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/ontogpt/utils/gpt4all_runner.py", line 5, in <module>
    import llm
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/llm/__init__.py", line 15, in <module>
    from .plugins import pm
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/llm/plugins.py", line 13, in <module>
    pm.load_setuptools_entrypoints("llm")
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/llm_gpt4all.py", line 1, in <module>
    from gpt4all import GPT4All as _GPT4All
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .gpt4all import Embed4All, GPT4All  # noqa
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/gpt4all.py", line 13, in <module>
    from . import pyllmodel
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 48, in <module>
    llmodel = load_llmodel_library()
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 43, in load_llmodel_library
    llmodel_lib = ctypes.CDLL(llmodel_dir)
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.so)
```

**Comment by caufieldjh** [comment]
Great - I just got an error very similar to this!
I'm going to open a separate thread for these: https://github.com/monarch-initiative/ontogpt/issues/221
