### ISSUE TITLE
Specify model does not work

### ISSUE THREAD

**Issue by kluo9** [monarch-initiative/ontogpt#191]
Hello,

I tried to specify model in the extraction but ontogpt can't recognize it.

`ontogpt extract -t mytemplate -i mytext.txt -m gpt-3.5-turbo-16k`

ERROR:ontogpt.clients.openai_client:OpenAI API connection error: This model's maximum context length is 4097 tokens. However, you requested 4584 tokens (1584 in the messages, 3000 in the completion). Please reduce the length of the messages or completion.
ERROR:ontogpt.clients.openai_client:OpenAI API connection error: This model's maximum context length is 4097 tokens. However, you requested 4584 tokens (1584 in the messages, 3000 in the completion). Please reduce the length of the messages or completion.
ERROR:ontogpt.clients.openai_client:OpenAI API connection error: This model's maximum context length is 4097 tokens. However, you requested 4584 tokens (1584 in the messages, 3000 in the completion). Please reduce the length of the messages or completion.
Traceback (most recent call last):
  File "/opt/conda/bin/ontogpt", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/cli.py", line 311, in extract
    results = ke.extract_from_text(text, target_class_def)
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/engines/spires_engine.py", line 89, in extract_from_text
    raw_text = self._raw_extract(text, cls, object=object)
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/engines/spires_engine.py", line 358, in _raw_extract
    payload = self.client.complete(prompt)
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/clients/openai_client.py", line 72, in complete
    raise e
  File "/opt/conda/lib/python3.9/site-packages/ontogpt/clients/openai_client.py", line 51, in complete
    response = openai.ChatCompletion.create(
  File "/opt/conda/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/opt/conda/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/opt/conda/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/opt/conda/lib/python3.9/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4584 tokens (1584 in the messages, 3000 in the completion). Please reduce the length of the messages or completion.

Is there a bug? 

Thanks!

**Comment by caufieldjh** [comment]
Hi @kluo9, looks like the model name option isn't getting passed properly. A fix is on the way.

**Comment by caufieldjh** [comment]
Should work as of the fix above, with an official release coming soon.
