### ISSUE TITLE
`recipe-extract` command fails with `AttributeError`

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#195]
Calls to the `recipe-extract` command fail with the following:
```
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 771, in recipe_extract
    results.extracted_object.url = url
AttributeError: 'NoneType' object has no attribute 'url'
```

Running in verbose shows that a response is returned from the model, it just isn't grounded.
My suspicion is either: 
* That cli.py line 769 is
```
results = ke.extract_from_text(text=text, show_prompt=show_prompt)
```
but it should also define the target class, even though in this command we don't provide that as an option (and the method is just parsing it as a default of None)

* The `ExtractionResult` legitimately is getting set to None. This seems to be true anyway based on the debug output of 
```
extracted_object=None named_entities=[]
```

**Comment by caufieldjh** [comment]
Looks like this command isn't getting the `models` parameter specified correctly, either (same solution as #192), which doesn't seem to be causing the error but isn't helping.
