### ISSUE TITLE
Error installing OntoGPT

### ISSUE THREAD

**Issue by kluo9** [monarch-initiative/ontogpt#200]
Hi, I tried to install Ontogpt on Azure machine learning studio, and the package was installed alright. But when I type 'ontogpt', the following error message occurred:

Traceback (most recent call last):
  File "/anaconda/envs/py39/bin/ontogpt", line 3, in <module>
    from ontogpt.cli import main
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/luok81/code/Users/luok8/ontogpt/src/ontogpt/cli.py", line 30, in <module>
    from ontogpt.engines import create_engine
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/luok81/code/Users/luok8/ontogpt/src/ontogpt/engines/__init__.py", line 1, in <module>
    from ontogpt.engines.resolver import create_engine  # noqa
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/luok81/code/Users/luok8/ontogpt/src/ontogpt/engines/resolver.py", line 6, in <module>
    from ontogpt.engines.enrichment import EnrichmentEngine
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/luok81/code/Users/luok8/ontogpt/src/ontogpt/engines/enrichment.py", line 19, in <module>
    from ontogpt.utils.gene_set_utils import (
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/luok81/code/Users/luok8/ontogpt/src/ontogpt/utils/gene_set_utils.py", line 26, in <module>
    session = requests_cache.CachedSession(GENE_REQUESTS_CACHE)
  File "/anaconda/envs/py39/lib/python3.9/site-packages/requests_cache/session.py", line 61, in __init__
    self.cache = init_backend(cache_name, backend, serializer=serializer, **kwargs)
  File "/anaconda/envs/py39/lib/python3.9/site-packages/requests_cache/backends/__init__.py", line 91, in init_backend
    return BACKEND_CLASSES[backend](cache_name, **kwargs)
  File "/anaconda/envs/py39/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 62, in __init__
    self.responses: SQLiteDict = SQLiteDict(db_path, table_name='responses', **skwargs)
  File "/anaconda/envs/py39/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 208, in __init__
    self.init_db()
  File "/anaconda/envs/py39/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 220, in init_db
    con.execute(
sqlite3.OperationalError: database is locked

 I was able to install the package locally so I don't know if this is a problem of the platform (Azure)?

**Comment by caufieldjh** [comment]
Hi @kluo9,
I haven't seen this error before, but I agree with your suspicion that this is related to the Azure environment.
The database referenced by these errors isn't used by all OntoGPT functions - it's limited to the gene enrichment functions - so there may be a bugfix we can implement to handle cases like this.

In the meantime, there may be some workarounds for accessing this database on Azure. This issue may be related to the CIFS file system that Azure uses; I think it's similar to this issue: https://github.com/iterative/dvc/issues/9145
If you can get OntoGPT to create the db in the first place, this solution may work: https://stackoverflow.com/a/66567897
The other solution appears to be to move the database or the whole OntoGPT directory to a different directory on the filesystem (like /tmp) but it looks like this may be a shared instance, so that may not be work.

I'll add a quick fix that should enable the rest of OntoGPT to work without that database, at least.

**Comment by caufieldjh** [comment]
@kluo9 The fix is now in the repository version here and will be in the next OntoGPT release - look for that in the next few days.

**Comment by kluo9** [comment]
Hi @caufieldjh,

Follow up on the issue. For the new release I still have some trouble after running 'ontogpt complete example.txt':

Traceback (most recent call last):
  File "/anaconda/envs/py39/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/anaconda/envs/py39/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda/envs/py39/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/anaconda/envs/py39/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda/envs/py39/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda/envs/py39/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/luok82/code/Users/luok8/ontogpt/src/ontogpt/cli.py", line 1536, in complete
    results = c.complete(text, show_prompt)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/luok82/code/Users/luok8/ontogpt/src/ontogpt/clients/openai_client.py", line 38, in complete
    res = cur.execute("SELECT payload FROM cache WHERE prompt=? AND engine=?", (prompt, engine))
sqlite3.OperationalError: no such table: cache


Is it still related to database problem?
