### ISSUE TITLE
WARNING:root:Could not find any mappings for fplx:Interferon

### ISSUE THREAD

**Issue by suyanpengzhang** [monarch-initiative/ontogpt#217]
I'm trying to follow the example provided in [Strategy 1: Knowledge extraction using SPIRES](https://github.com/monarch-initiative/ontogpt#strategy-1-knowledge-extraction-using-spires)

in command line I used: ontogpt extract -t gocam.GoCamAnnotations -i gocam-betacat.txt    

But I got this warning: WARNING:root:Could not find any mappings for fplx:Interferon

Then the error message pops up: 

Traceback (most recent call last):
  File "/Users/suyanpengzhang/opt/anaconda3/bin/ontogpt", line 8, in <module>
    sys.exit(main())
  File "/Users/suyanpengzhang/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/suyanpengzhang/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/suyanpengzhang/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/suyanpengzhang/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/suyanpengzhang/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/suyanpengzhang/opt/anaconda3/lib/python3.9/site-packages/ontogpt/cli.py", line 337, in extract
    write_extraction(results, output, output_format, ke)
  File "/Users/suyanpengzhang/opt/anaconda3/lib/python3.9/site-packages/ontogpt/cli.py", line 107, in write_extraction
    output.write(dump_minimal_yaml(results).encode("utf-8"))
TypeError: write() argument must be str, not bytes

**Comment by caufieldjh** [comment]
Hi @suyanpengzhang - thanks for trying out OntoGPT!
The newest version (0.3.3) should fix the TypeError problem for you - please try updating and let me know if the error persists.

For this one:
```But I got this warning: WARNING:root:Could not find any mappings for fplx:Interferon```
this isn't really an error that is likely to impact results, but rather an instance in which a term was found that ontogpt couldn't find a better identifier for (specifically, using the [NodeNormalizer ](https://github.com/TranslatorSRI/NodeNormalization) tool). That makes sense here because the input definitely includes the term `interferon` but this could resolve to several different identifiers.
