### ISSUE TITLE
Missing libraries after pip install (OSError)

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#221]
@serenalotreck said in https://github.com/monarch-initiative/ontogpt/issues/188#issuecomment-1735869236_:
              After installation, I get a different error when I run `ontogpt --help`:

```
Traceback (most recent call last):
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/bin/ontogpt", line 5, in <module>
    from ontogpt.cli import main
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/ontogpt/cli.py", line 34, in <module>
    from ontogpt.engines.gpt4all_engine import GPT4AllEngine  # type: ignore
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/ontogpt/engines/gpt4all_engine.py", line 34, in <module>
    from ontogpt.utils.gpt4all_runner import chain_gpt4all_model, set_up_gpt4all_model
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/ontogpt/utils/gpt4all_runner.py", line 5, in <module>
    import llm
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/llm/__init__.py", line 15, in <module>
    from .plugins import pm
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/llm/plugins.py", line 13, in <module>
    pm.load_setuptools_entrypoints("llm")
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/llm_gpt4all.py", line 1, in <module>
    from gpt4all import GPT4All as _GPT4All
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .gpt4all import Embed4All, GPT4All  # noqa
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/gpt4all.py", line 13, in <module>
    from . import pyllmodel
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 48, in <module>
    llmodel = load_llmodel_library()
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 43, in load_llmodel_library
    llmodel_lib = ctypes.CDLL(llmodel_dir)
  File "/mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /mnt/home/lotrecks/anaconda3/envs/graphs/lib/python3.10/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.so)
```

I got a similar error after a pip install of ontogpt 0.3.3 in a fresh venv:

```
$ ontogpt --help
Traceback (most recent call last):
  File "/home/harry/temp/tempog/bin/ontogpt", line 5, in <module>
    from ontogpt.cli import main
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/ontogpt/cli.py", line 34, in <module>
    from ontogpt.engines.gpt4all_engine import GPT4AllEngine  # type: ignore
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/ontogpt/engines/gpt4all_engine.py", line 34, in <module>
    from ontogpt.utils.gpt4all_runner import chain_gpt4all_model, set_up_gpt4all_model
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/ontogpt/utils/gpt4all_runner.py", line 5, in <module>
    import llm
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/llm/__init__.py", line 15, in <module>
    from .plugins import pm
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/llm/plugins.py", line 13, in <module>
    pm.load_setuptools_entrypoints("llm")
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/pluggy/_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/llm_gpt4all.py", line 1, in <module>
    from gpt4all import GPT4All as _GPT4All
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .gpt4all import Embed4All, GPT4All  # noqa
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/gpt4all/gpt4all.py", line 13, in <module>
    from . import pyllmodel
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/gpt4all/pyllmodel.py", line 48, in <module>
    llmodel = load_llmodel_library()
  File "/home/harry/temp/tempog/lib/python3.9/site-packages/gpt4all/pyllmodel.py", line 43, in load_llmodel_library
    llmodel_lib = ctypes.CDLL(llmodel_dir)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/harry/temp/tempog/lib/python3.9/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.so)
```

**Comment by caufieldjh** [comment]
This would appear to be the core problem: https://github.com/nomic-ai/gpt4all/issues/1436
So the `gpt4all` package is reliant on libraries that may not be present in all OS's or versions.

The fix for now is to install an older `gpt4all`:
```
pip install gpt4all==1.0.8
```

**Comment by serenalotreck** [comment]
That worked, thank you!

**Comment by caufieldjh** [comment]
I'm going to close this but will consider moving the gpt4all-related components (through the llm-gpt4all plugin) to fully optional dependencies.

**Comment by caufieldjh** [comment]
As a follow-up to this and to remind myself to update the docs:
The library in question may still be present on the system.
On mine, the error stated the library was not found at `/lib/x86_64-linux-gnu/libstdc++.so.6`, but that's because it was present at `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`.
So running 
```bash
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
```
should help, as should adding that to the `~/.bashrc`
