### ISSUE TITLE
`embed` command raises `InvalidRequestError` from OpenAI API

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#240]
Attempting to retrieve embeddings raises an error from the API:
```
$ ontogpt embed "obstreperous muskrat"
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 1052, in embed
    resp = client.embeddings(text)
  File "/home/harry/ontogpt/src/ontogpt/clients/openai_client.py", line 167, in embeddings
    response = openai.Embedding.create(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: you must provide a model parameter
```

The issue is that the `embeddings` function in `openai_client.py` sets the model default to an empty string, and while it subsequently checks to see if the model is specified, it's still left as an empty string.

Attempting to set the model with -m leads to the same error.

Setting the default to `"text-embedding-ada-002"` fixes it but this should be assigned through the CLI instead.

**Comment by caufieldjh** [comment]
There's a related error on line 73 of `gene_set_utils.py`:

```python
def parse_gene_set(input_path: Union[str, Path], format: str = "") -> GeneSet:
```

So in this case, the format doesn't get set properly.
