### ISSUE TITLE
Need guidance with custom schema

### ISSUE THREAD

**Issue by Gaurang111** [monarch-initiative/ontogpt#260]
Hi @caufieldjh 

I am working on a diabetes project where I am using Ontogpt. I want to build and install a custom diabetes template, I am following a custom schema page in Documentary and was able to build and install it using the LinkML gen-pedantic.

diabetes_schema.yaml looks like this:

```
id: http://w3id.org/ontogpt/diabetes_schema
name: diabetes_schema
title: Diabetes Information Schema
description: >-
  A schema for extracting information related to diabetes.

license: https://creativecommons.org/publicdomain/zero/1.0/
prefixes:
  linkml: https://w3id.org/linkml/
  diabetes: http://w3id.org/ontogpt/diabetes_schema/
  SNOMED: http://snomed.info/sct

default_prefix: diabetes
default_range: string

imports:
  - linkml:types
  - core

classes:
  DiabetesInformation:
    tree_root: true
    attributes:
      symptoms:
        description: semicolon-separated list of symptoms associated with diabetes
        multivalued: true
        range: Symptom
      risk_factors:
        description: semicolon-separated list of risk factors for diabetes
        multivalued: true
        range: RiskFactor
      treatments:
        description: semicolon-separated list of treatments for diabetes
        multivalued: true
        range: Treatment

  Symptom:
    is_a: NamedEntity
    annotations:
      annotators: sqlite:obo:sct
    id_prefixes:
      - SNOMED

  RiskFactor:
    is_a: NamedEntity
    annotations:
      annotators: sqlite:obo:sct
    id_prefixes:
      - SNOMED

  Treatment:
    is_a: NamedEntity
    annotations:
      annotators: sqlite:obo:sct
    id_prefixes:
      - SNOMED
```

creates diabetes_schema.py using:
`gen-pydantic --pydantic_version 2 diabetes_schema.yaml > diabetes_schema.py
`

then I moved .yaml and .py files to the template directory.

input.txt looks like this:

```
Diabetes is a chronic condition that affects the body's ability to process blood sugar. Common symptoms include increased thirst, frequent urination, and unexplained weight loss. Risk factors for diabetes include family history, unhealthy diet, and lack of physical activity. Treatment options may include medication, insulin therapy, and lifestyle changes such as a healthy diet and regular exercise.
```

 However, when I run the command

`ontogpt extract -t diabetes_schema -i input.txt `

I get the following HTTPError: 

```
INFO:root:API KEY path = C:\Users\goran\AppData\Local\ontology-access-kit\ontology-access-kit\ncbi-email-apikey.txt
INFO:root:API KEY path = C:\Users\goran\AppData\Local\ontology-access-kit\ontology-access-kit\ncbi-key-apikey.txt
WARNING:rdflib.term:C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\linkml_runtime\linkml_model\model\schema\types does not look like a valid URI, trying to serialize this will break.
Traceback (most recent call last):        
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Scripts\ontogpt.exe\__main__.py", line 7, in <module>
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\ontogpt\cli.py", line 336, in extract
    results = ke.extract_from_text(text=text, cls=target_class_def, show_prompt=show_prompt)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\ontogpt\engines\spires_engine.py", line 97, in extract_from_text
    extracted_object = self.parse_completion_payload(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\ontogpt\engines\spires_engine.py", line 559, in parse_completion_payload
    return self.ground_annotation_object(raw, cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\ontogpt\engines\spires_engine.py", line 631, in ground_annotation_object
    obj = self.normalize_named_entity(val, slot.range)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\ontogpt\engines\knowledge_engine.py", line 350, in normalize_named_entity
    for obj_id in self.groundings(text, cls):
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\ontogpt\engines\knowledge_engine.py", line 541, in groundings
    self.annotators[annotator] = get_adapter(annotator)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\oaklib\selector.py", line 152, in get_adapter
    return res.implementation_class(res, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 26, in __init__
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\oaklib\implementations\sqldb\sql_implementation.py", line 329, in __post_init__      
    db_path = OAKLIB_MODULE.ensure_gunzip(url=url, autoclean=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\pystow\impl.py", line 297, in ensure_gunzip
    path = self.ensure(
           ^^^^^^^^^^^^
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\pystow\impl.py", line 171, in ensure
    utils.download(
  File "C:\Users\goran\PycharmProjects\pythonProject\ontogpt\venv\Lib\site-packages\pystow\utils.py", line 360, in download
    urlretrieve(url, path, reporthook=t.update_to, **kwargs)  # noqa:S310
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goran\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\goran\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

I don't know how to solve it. Can you please help me here?

**Comment by caufieldjh** [comment]
Hi @Gaurang111, I was able to reproduce this error on my machine. 
I can understand how the HTTPError is confusing, since the real issue here is that the adapter `sqlite:obo:sct` doesn't exist.
It can be replaced with `bioportal:SNOMEDCT` - and in this case the id_prefix for each should be `SNOMEDCT`.
When I do that, then make the Pydantic classes and run the extract command again, this is what I get:
```yaml
$ ontogpt extract -t diabetes_schema -i input.txt
---
input_text: Diabetes is a chronic condition that affects the body's ability to process
  blood sugar. Common symptoms include increased thirst, frequent urination, and unexplained
  weight loss. Risk factors for diabetes include family history, unhealthy diet, and
  lack of physical activity. Treatment options may include medication, insulin therapy,
  and lifestyle changes such as a healthy diet and regular exercise.
raw_completion_output: |-
  symptoms: increased thirst; frequent urination; unexplained weight loss
  risk_factors: family history; unhealthy diet; lack of physical activity
  treatments: medication; insulin therapy; lifestyle changes
prompt: |+
  From the text below, extract the following entities in the following format:

  symptoms: <semicolon-separated list of symptoms associated with diabetes>
  risk_factors: <semicolon-separated list of risk factors for diabetes>
  treatments: <semicolon-separated list of treatments for diabetes>


  Text:
  Diabetes is a chronic condition that affects the body's ability to process blood sugar. Common symptoms include increased thirst, frequent urination, and unexplained weight loss. Risk factors for diabetes include family history, unhealthy diet, and lack of physical activity. Treatment options may include medication, insulin therapy, and lifestyle changes such as a healthy diet and regular exercise.

  ===

extracted_object:
  symptoms:
    - SNOMEDCT:249477003
    - SNOMEDCT:70232002
    - SNOMEDCT:422868009
  risk_factors:
    - SNOMEDCT:35359004
    - AUTO:unhealthy%20diet
    - SNOMEDCT:68130003
  treatments:
    - AUTO:medication
    - SNOMEDCT:67866001
    - SNOMEDCT:134436002
named_entities:
  - id: SNOMEDCT:249477003
    label: increased thirst
  - id: SNOMEDCT:70232002
    label: frequent urination
  - id: SNOMEDCT:422868009
    label: unexplained weight loss
  - id: SNOMEDCT:35359004
    label: family history
  - id: AUTO:unhealthy%20diet
    label: unhealthy diet
  - id: SNOMEDCT:68130003
    label: lack of physical activity
  - id: AUTO:medication
    label: medication
  - id: SNOMEDCT:67866001
    label: insulin therapy
  - id: SNOMEDCT:134436002
    label: lifestyle changes
```

You may find better mapping for these classes with more specific ontologies (e.g., Human Phenotype Ontology for symptoms), of course, but SNOMEDCT will certainly help with mapping.

**Comment by Gaurang111** [comment]
Perfect! it works, Thank you very much! you are a savior.

**Comment by caufieldjh** [comment]
Happy to help!
