### ISSUE TITLE
`PermissionError` when running example from the docs

### ISSUE THREAD

**Issue by serenalotreck** [monarch-initiative/ontogpt#264]
From comments on #246:

After upgrading `pydantic` and downgrading `gpt4all` as discussed in #188 and #221, `ontogpt --help` runs, but running the toy example from the docs gives the following error:

```
Traceback (most recent call last):
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/bin/ontogpt", line 8, in <module>
    sys.exit(main())
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/ufs18/home-118/lotrecks/haai_vanburen_lab/ontogpt/src/ontogpt/cli.py", line 316, in extract
    ke = SPIRESEngine(template=template, model=model_name, **kwargs)
  File "<string>", line 23, in __init__
  File "/mnt/ufs18/home-118/lotrecks/haai_vanburen_lab/ontogpt/src/ontogpt/engines/knowledge_engine.py", line 167, in __post_init__
    self.encoding = tiktoken.encoding_for_model(self.client.model)
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/tiktoken/model.py", line 97, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/tiktoken/load.py", line 116, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "/mnt/home/lotrecks/anaconda3/envs/ontogpt/lib/python3.9/site-packages/tiktoken/load.py", line 52, in read_file_cached
    with open(tmp_filename, "wb") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/data-gym-cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4.9f5ead06-73d0-49e6-a241-6267d8a0a3a1.tmp'
```

**Comment by serenalotreck** [comment]
Hi @caufieldjh,

I came back to this today, and when I ran the toy example, I got a new error:

```
You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

Howeverm I was operating on `ontopgt==0.3.3` (installed from my local copy of the repo), so when I pulled and updated to `0.3.4`, everything ran!! Closing this since it appears this bug was at least solved for me in the newest version.

Thanks!
