### ISSUE TITLE
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by peiyaoli** [monarch-initiative/ontogpt#272]
Hi, I followed every step of tutorial on installation and setup.

But this error pops up after 
```
ontogpt --help
```
Here is full stack:
```
Traceback (most recent call last):
  File "/home/peiyaoli/miniconda3/envs/GPT/bin/ontogpt", line 5, in <module>
    from ontogpt.cli import main
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/ontogpt/cli.py", line 34, in <module>
    from ontogpt.engines.gpt4all_engine import GPT4AllEngine  # type: ignore
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/ontogpt/engines/gpt4all_engine.py", line 34, in <module>
    from ontogpt.utils.gpt4all_runner import chain_gpt4all_model, set_up_gpt4all_model
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/ontogpt/utils/gpt4all_runner.py", line 5, in <module>
    import llm
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/llm/__init__.py", line 15, in <module>
    from .plugins import pm
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/llm/plugins.py", line 13, in <module>
    pm.load_setuptools_entrypoints("llm")
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/pluggy/_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/llm_gpt4all.py", line 1, in <module>
    from gpt4all import GPT4All as _GPT4All
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .gpt4all import Embed4All, GPT4All  # noqa
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/gpt4all/gpt4all.py", line 18, in <module>
    from . import pyllmodel
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/gpt4all/pyllmodel.py", line 42, in <module>
    llmodel = load_llmodel_library()
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/site-packages/gpt4all/pyllmodel.py", line 32, in load_llmodel_library
    lib = ctypes.CDLL(str(MODEL_LIB_PATH / f"libllmodel.{ext}"))
  File "/home/peiyaoli/miniconda3/envs/GPT/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
```

How could I resolve this issue?

**Comment by peiyaoli** [comment]
Hi, I tried the solution you mentioned to use lower version of gpt4all like `1.0.8`.
But now it says `OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found`
🤣
BTW, my ontogpt version is `0.3.3`

**Comment by caufieldjh** [comment]
OK, you may want to try the newest release of `ontogpt`, 0.3.4, just to ensure dependencies are all set up as expected.
The core problem is still with `gpt4all` and the libraries it expects to be available (see https://github.com/nomic-ai/gpt4all/issues/1480)
It's largely going to be a function of your OS. That package is apparently built on Ubuntu 22.04 (see here: https://github.com/nomic-ai/gpt4all/issues/1300).
I was waiting on some upstream changes in the `llm` plugin for gpt4all before fully modularizing the non-OpenAI model clients, but since none of these libraries are used outside `gpt4all`, it looks like it's time to make that part optional.

**Comment by caufieldjh** [comment]
As of the new release (0.3.6), gpt4all dependencies are optional, so the rest should install and run without issue. Please give it a try!

**Comment by caufieldjh** [comment]
Leaving a note here that I ran into this issue again today (after installing `llm-gpt4all` 0.2) - and didn't appear to have the requested library (`GLIBCXX_3.4.29`) anywhere on my system.
I got the requested library by installing new libstdc++6:
```
sudo apt-get upgrade libstdc++6
```
Then I checked on what was available:
```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_3.4.31
GLIBCXX_3.4.32
GLIBCXX_TUNABLES
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

Of course, then I got another error about a missing library when trying to `import llm`:
```
OSError: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/harry/ontogpt/.venv/lib/python3.9/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.so)
```

Ah, so my glibc is also out of date and I'm on Ubuntu 20.04, which doesn't really support the newer glibc versions.
So I can either make from scratch or update to 22.04.

**Comment by caufieldjh** [comment]
Upgrading to Ubuntu 22.04 (and subsequently uninstalling + reinstalling Poetry, then reinstalling OntoGPT with `poetry install --extras gpt4all`) appears to solve this issue.

I'm going to consider this issue closed, not because I'm completely happy with the result, but because there's a set of conditions under which it should definitely work (and it isn't Ubuntu 20.04 or older).
