### ISSUE TITLE
Webapp encounters Internal Service Error due to missing attribute

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#294]
Running `web-ontogpt` and attempting to process the simple spaghetti recipe with the recipe schema fails, raising this stack trace:
```
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/harry/ontogpt/src/ontogpt/webapp/main.py", line 60, in form_post
    html_exporter.export(extraction_output=ann, output=output)
  File "/home/harry/ontogpt/src/ontogpt/io/html_exporter.py", line 38, in export
    self.export_results(extraction_output.extracted_object, extraction_output)
  File "/home/harry/ontogpt/src/ontogpt/io/html_exporter.py", line 54, in export_results
    self.export_object(obj, extraction_output, -1)
  File "/home/harry/ontogpt/src/ontogpt/io/html_exporter.py", line 62, in export_object
    for field in obj.__fields__.values():
AttributeError: 'NoneType' object has no attribute '__fields__'
```

**Comment by caufieldjh** [comment]
For comparison, running the same input with the drug schema on the webapp encounters a similar but non-identical error:
```
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/harry/ontogpt/src/ontogpt/webapp/main.py", line 60, in form_post
    html_exporter.export(extraction_output=ann, output=output)
  File "/home/harry/ontogpt/src/ontogpt/io/html_exporter.py", line 38, in export
    self.export_results(extraction_output.extracted_object, extraction_output)
  File "/home/harry/ontogpt/src/ontogpt/io/html_exporter.py", line 54, in export_results
    self.export_object(obj, extraction_output, -1)
  File "/home/harry/ontogpt/src/ontogpt/io/html_exporter.py", line 64, in export_object
    self.h3(field.name)
AttributeError: 'FieldInfo' object has no attribute 'name'
```
