### ISSUE TITLE
Disk quota exceeded

### ISSUE THREAD

**Issue by Vishal-Joshi** [monarch-initiative/ontogpt#301]
I am trying to run ontogpt as a singularity image on HPC cluster. The image starts to run but since it needs to download the supporting ontologies like Gene Ontology (GO) & it seems to use my home folder for this, by default.

We have disk quota applied in our home folders which is just bare minimum therefore not enough space for the downloads to finish I guess. I was trying to read from 
```
ontogpt --help
``` 
and [ontogpt published documentation here](https://monarch-initiative.github.io/ontogpt/)

I could not locate any property to change the location of download or change the working directory to be used by ontogpt. How can I do that?

I am getting this exception stacktrace
```
ERROR:ontogpt.engines.knowledge_engine:Error with SqlImplementation(resource=OntologyResource(slug='obo:pr', directory=None, scheme='sqlite', format=None, url=None, readonly=False, provider=None, local=False, in_
memory=False, data=None, implementation_class=<class 'oaklib.implementations.sqldb.sql_implementation.SqlImplementation'>, import_depth=None), strict=False, _multilingual=None, autosave=True, exclude_owl_top_and_
bottom=True, ontology_metamodel_mapper=None, _converter=None, auto_relax_axioms=None, cache_lookups=False, _edge_index=None, _entailed_edge_index=None, functional_writer=None, _association_index=None, normalizers
=[], engine=Engine(sqlite:////homes/vjoshi/.data/oaklib/pr.db), _session=<sqlalchemy.orm.session.Session object at 0x7fa9aa5e93f0>, _connection=None, _ontology_metadata_model=None, _prefix_map=None, _information_
content_cache=None, _relationships_by_subject_index=None, max_items_for_in_clause=1000, can_store_associations=False) for Spermitin: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT DISTINCT statements.subject AS statements_subject
FROM statements
WHERE statements.predicate IN (?) AND statements.value LIKE ?]
[parameters: ('rdfs:label', 'Spermitin')]
(Background on this error at: https://sqlalche.me/e/20/4xp6)
^MDownloading go.db.gz: 0.00B [00:00, ?B/s]^MDownloading go.db.gz:   0%|                                                                                                  | 8.00k/348M [00:00<5:46:56, 17.5kB/s]^MDo
wnloading go.db.gz:   0%|                                                                                                     | 56.0k/348M [00:00<53:57, 113kB/s]^MDownloading go.db.gz:   0%|
                                                                                | 288k/348M [00:00<11:02, 550kB/s]^MDownloading go.db.gz:   0%|▎
                               | 1.10M/348M [00:00<02:56, 2.06MB/s]^MDownloading go.db.gz:   1%|▉                                                                                                   | 3.23M/348M [00
:01<01:03, 5.69MB/s]^MDownloading go.db.gz:   2%|██▎                                                                                                 | 8.09M/348M [00:01<00:26, 13.7MB/s]^MDownloading go.db.gz:   3
%|███▎                                                                                                | 11.4M/348M [00:01<00:22, 16.0MB/s]^MDownloading go.db.gz:   4%|████▏
                                                       | 14.6M/348M [00:01<00:19, 17.6MB/s]^MDownloading go.db.gz:   5%|████▉
        | 17.0M/348M [00:01<00:20, 16.9MB/s]^MDownloading go.db.gz:   6%|█████▌                                                                                              | 19.4M/348M [00:01<00:21, 16.4MB/s]^MD
ownloading go.db.gz:   6%|██████▏                                                                                             | 21.7M/348M [00:02<00:21, 16.1MB/s]^MDownloading go.db.gz:   7%|██████▉
                                                                               | 24.1M/348M [00:02<00:21, 16.0MB/s]^MDownloading go.db.gz:   8%|███████▌
                                | 26.5M/348M [00:02<00:21, 15.9MB/s]^MDownloading go.db.gz:   8%|████████▎                                                                                           | 29.0M/348M [0
0:02<00:19, 16.9MB/s]^MDownloading go.db.gz:   9%|████████▋                                                                                           | 30.2M/348M [00:02<00:21, 15.6MB/s]^MDownloading go.db.gz:
9%|█████████▍                                                                                          | 32.6M/348M [00:02<00:19, 16.9MB/s]^MDownloading go.db.gz:  10%|█████████▋
                                                        | 33.9M/348M [00:02<00:21, 15.5MB/s]^MDownloading go.db.gz:  10%|██████████▍
         | 36.2M/348M [00:03<00:19, 16.5MB/s]^MDownloading go.db.gz:  11%|██████████▋                                                                                         | 37.1M/348M [00:03<00:23, 14.2MB/s]^M
Downloading go.db.gz:  11%|███████████▏                                                                                        | 38.9M/348M [00:03<00:22, 14.3MB/s]^MDownloading go.db.gz:  11%|███████████▍
                                                                                | 39.8M/348M [00:03<00:25, 12.6MB/s]^MDownloading go.db.gz:  12%|███████████▉
                                 | 41.6M/348M [00:03<00:24, 13.3MB/s]^MDownloading go.db.gz:  12%|████████████▏                                                                                       | 42.5M/348M [
00:03<00:26, 12.0MB/s]^MDownloading go.db.gz:  13%|████████████▋                                                                                       | 44.3M/348M [00:03<00:24, 13.0MB/s]^MDownloading go.db.gz:
13%|████████████▉                                                                                       | 45.1M/348M [00:03<00:28, 11.2MB/s]^MDownloading go.db.gz:  13%|█████████████▍
                                                         | 46.8M/348M [00:03<00:25, 12.2MB/s]^MDownloading go.db.gz:  14%|█████████████▋
          | 47.5M/348M [00:04<00:30, 10.4MB/s]^MDownloading go.db.gz:  14%|██████████████                                                                                      | 48.8M/348M [00:04<00:29, 10.6MB/s]
^MDownloading go.db.gz:  14%|██████████████▏                                                                                     | 49.5M/348M [00:04<00:33, 9.40MB/s]^MDownloading go.db.gz:  15%|██████████████▌
                                                                                  | 50.9M/348M [00:04<00:31, 9.94MB/s]^MDownloading go.db.gz:  15%|██████████████▊
                                    | 51.6M/348M [00:04<00:34, 8.93MB/s]^MDownloading go.db.gz:  15%|███████████████▏                                                                                    | 52.9M/348M [00:04<00:31, 9.74MB/s]^MDownloading go.db.gz:  15%|███████████████▍                                                                                    | 53.7M/348M [00:04<00:34, 8.85MB/s]^MDownloading go.db.gz:  16%|███████████████▊                                                                                    | 55.1M/348M [00:04<00:31, 9.73MB/s]^MDownloading go.db.gz:  16%|████████████████                                                                                    | 55.8M/348M [00:05<00:34, 8.83MB/s]^MDownloading go.db.gz:  16%|████████████████▍                                                                                   | 57.2M/348M [00:05<00:31, 9.80MB/s]^MDownloading go.db.gz:  17%|████████████████▋                                                                                   | 58.0M/348M [00:05<00:34, 8.94MB/s]^MDownloading go.db.gz:  17%|█████████████████                                                                                   | 59.4M/348M [00:05<00:30, 9.88MB/s]^MDownloading go.db.gz:  17%|█████████████████▎                                                                                  | 60.2M/348M [00:05<00:33, 9.01MB/s]^MDownloading go.db.gz:  18%|█████████████████▋                                                                                  | 61.7M/348M [00:05<00:29, 10.0MB/s]^MDownloading go.db.gz:  18%|█████████████████▉                                                                                  | 62.4M/348M [00:05<00:32, 9.12MB/s]^MDownloading go.db.gz:  18%|██████████████████▎                                                                                 | 63.6M/348M [00:05<00:35, 8.42MB/s]^M                                                                                                                                                                   ^MTraceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 274, in urlretrieve
    tfp.write(block)
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ontogpt", line 8, in <module>
    sys.exit(main())
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ontogpt/cli.py", line 336, in extract
    results = ke.extract_from_text(text=text, cls=target_class_def, show_prompt=show_prompt)
  File "/usr/local/lib/python3.10/dist-packages/ontogpt/engines/spires_engine.py", line 99, in extract_from_text
    extracted_object = self.parse_completion_payload(
  File "/usr/local/lib/python3.10/dist-packages/ontogpt/engines/spires_engine.py", line 562, in parse_completion_payload
    return self.ground_annotation_object(raw, cls)
  File "/usr/local/lib/python3.10/dist-packages/ontogpt/engines/spires_engine.py", line 632, in ground_annotation_object
    obj = self.ground_annotation_object(val, rng_cls)
  File "/usr/local/lib/python3.10/dist-packages/ontogpt/engines/spires_engine.py", line 634, in ground_annotation_object
    obj = self.normalize_named_entity(val, slot.range)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/ontogpt/engines/knowledge_engine.py", line 351, in normalize_named_entity
    for obj_id in self.groundings(text, cls):
  File "/usr/local/lib/python3.10/dist-packages/ontogpt/engines/knowledge_engine.py", line 546, in groundings
    self.annotators[annotator] = get_adapter(annotator)
  File "/usr/local/lib/python3.10/dist-packages/oaklib/selector.py", line 152, in get_adapter
    return res.implementation_class(res, **kwargs)
  File "<string>", line 26, in __init__
  File "/usr/local/lib/python3.10/dist-packages/oaklib/implementations/sqldb/sql_implementation.py", line 331, in __post_init__
    db_path = OAKLIB_MODULE.ensure_gunzip(url=url, autoclean=False)
  File "/usr/local/lib/python3.10/dist-packages/pystow/impl.py", line 297, in ensure_gunzip
    path = self.ensure(
  File "/usr/local/lib/python3.10/dist-packages/pystow/impl.py", line 171, in ensure
    utils.download(
  File "/usr/local/lib/python3.10/dist-packages/pystow/utils.py", line 360, in download
    urlretrieve(url, path, reporthook=t.update_to, **kwargs)  # noqa:S310
  File "/usr/lib/python3.10/urllib/request.py", line 257, in urlretrieve
    with tfp:
OSError: [Errno 122] Disk quota exceeded
```

**Comment by caufieldjh** [comment]
Hi @Vishal-Joshi - OntoGPT (or more specifically, OAK, since that's what handles ontology interfaces) uses the `pystow` package to handle downloads. Conveniently, `pystow` allows configuration of the download directory through an environment variable - see https://github.com/cthoyt/pystow#%EF%B8%8F%EF%B8%8F-configuration

I'm going to try this out and get back to you.

**Comment by caufieldjh** [comment]
Yes, the solution is to set the `PYSTOW_HOME` variable, so if you do something like
```bash
export PYSTOW_HOME='/tmp/'
```
then all the annotators will be saved to `/tmp/oaklib` instead of the home dir.

**Comment by Vishal-Joshi** [comment]
Perfect! it works

Cheers, closing this issue as well
