### ISSUE TITLE
Synonym function encounters TypeError

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#317]
The `synonym` function is currently broken, likely due to recent changes in how the CLI calls templates.
Example:
```
~/ontogpt$ ontogpt synonyms "otitis media" --context "healthcare"
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 878, in synonyms
    ke = SynonymEngine()
TypeError: SynonymEngine.__init__() missing 1 required positional argument: 'template_details'
```

**Comment by rebeccaito** [comment]
I see the same error when running `ontogpt diagnose`:
`TypeError: PhenoEngine.__init__() missing 1 required positional argument: 'template_details'`

**Comment by caufieldjh** [comment]
@rebeccaito This is fixed - please feel free to open a new issue if you still see this error with `diagnose`.
