### ISSUE TITLE
web-ontogpt raises KeyError

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#475]
_of course_ I had to discover this one during a live demo.

Running `web-ontogpt` raises a KeyError because it can't find the `description` key for one or more templates.

```
~/ontogpt$ web-ontogpt
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/web-ontogpt", line 3, in <module>
    from ontogpt.webapp.main import start
  File "/home/harry/ontogpt/src/ontogpt/webapp/main.py", line 24, in <module>
    all_templates = _get_templates()
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 2182, in _get_templates
    all_templates[identifier] = (data["name"], data["description"])
KeyError: 'description'
```

**Comment by caufieldjh** [comment]
In this case, all the repo templates have descriptions, but I had a local template without this value.
This is still a case to be caught in the CLI.
