### ISSUE TITLE
Using ollama/llama3 models fail when no openapi key is set

### ISSUE THREAD

**Issue by dnlbauer** [monarch-initiative/ontogpt#487]
The tool is currently not functioning if an OpenAI API key is not set, even when the user selects a model that does not require an OpenAI API key (e.g., `ollama/llama3`):

## Steps to reproduce

1. Install in virtual env
```bash
git clone https://github.com/monarch-initiative/ontogpt.git
cd ontogpt
uv venv
source .venv/bin/activate
python --version # 3.12.3
uv pip install .
```

2. Create test file `echo "One treatment for high blood pressure is carvedilol." > example.txt`

3. Run ontogpt with `-m ollama/llama3`:
```bash
❯ ontogpt -v extract -i example.txt -t drug -m ollama/llama3
INFO:root:Logger root set to level 20
INFO:root:Input file: example.txt
INFO:root:Input text: One treatment for high blood pressure is carvedilol.

INFO:ontogpt.io.template_loader:Loading schema for drug
INFO:linkml_runtime.utils.schemaview:Importing core as core from source /home/dbauer/projects/ontogpt/src/ontogpt/templates/drug.yaml; base_dir=/home/dbauer/projects/ontogpt/src/ontogpt/templates
INFO:linkml_runtime.utils.schemaview:Importing linkml:types as /home/dbauer/projects/ontogpt/.venv/lib/python3.12/site-packages/linkml_runtime/linkml_model/model/schema/types from source /home/dbauer/projects/ontogpt/src/ontogpt/templates/drug.yaml; base_dir=None
INFO:ontogpt.io.template_loader:Getting class for template drug
INFO:root:Using template DrugMechanism
INFO:root:API KEY path = /home/dbauer/.config/ontology-access-kit/openai-apikey.txt
Traceback (most recent call last):
  File "/home/dbauer/projects/ontogpt/.venv/bin/ontogpt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dbauer/projects/ontogpt/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbauer/projects/ontogpt/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dbauer/projects/ontogpt/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbauer/projects/ontogpt/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbauer/projects/ontogpt/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbauer/projects/ontogpt/src/ontogpt/cli.py", line 490, in extract
    ke = SPIRESEngine(
         ^^^^^^^^^^^^^
  File "<string>", line 29, in __init__
  File "/home/dbauer/projects/ontogpt/src/ontogpt/engines/knowledge_engine.py", line 242, in __post_init__
    self.client = LLMClient(
                  ^^^^^^^^^^
  File "<string>", line 11, in __init__
  File "/home/dbauer/projects/ontogpt/src/ontogpt/clients/llm_client.py", line 51, in __post_init__
    self.api_key = get_apikey_value("openai")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbauer/projects/ontogpt/.venv/lib/python3.12/site-packages/oaklib/utilities/apikey_manager.py", line 47, in get_apikey_value
    raise ValueError(f"No API key found in: {path}")
ValueError: No API key found in: /home/dbauer/.config/ontology-access-kit/openai-apikey.txt
```

## Workaround
I was able to get it to run by setting a "fake" api key for openai. It seems like ontogpt is using the correct model, but requires the api key to be present:

```bash
runoak set-apikey -e openai "a-fake-api-key"
ontogpt extract -i example.txt -t drug -m ollama/llama3 # works!
```

**Comment by caufieldjh** [comment]
Fixed by #488
