### ISSUE TITLE
Conflicting URIs across templates

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#94]
Running `make` for all projects/templates currently produces this error:
```
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/gen-project", line 8, in <module>
    sys.exit(cli())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/generators/projectgen.py", line 260, in cli
    gen.generate(yamlfile, project_config)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/generators/projectgen.py", line 149, in generate
    gen = gen_cls(local_path, **all_gen_args)
  File "<string>", line 23, in __init__
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/generators/graphqlgen.py", line 26, in __post_init__
    super().__post_init__()
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/generator.py", line 189, in __post_init__
    self._initialize_using_schemaloader(schema)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/generator.py", line 232, in _initialize_using_schemaloader
    loader.resolve()
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/schemaloader.py", line 166, in resolve
    merge_schemas(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/mergeutils.py", line 48, in merge_schemas
    merge_dicts(
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/linkml/utils/mergeutils.py", line 147, in merge_dicts
    raise ValueError(
ValueError: Conflicting URIs (http://w3id.org/ontogpt/gocam, https://w3id.org/ontogpt/biological_process) for item: Gene
make: *** [Makefile:41: projects/all] Error 1
```

This happens after an attempt to run
```
poetry run gen-project src/ontogpt/templates/all.yaml -d projects/all && cp -pr projects/all/docs docs/all
```
so that conflict makes sense: two different templates try to define Gene.
Who gets to say what a Gene is?
Or should we skip trying to merge all into one template?

**Comment by alita-moore** [comment]
I'm having the same problem

**Comment by cmungall** [comment]
Let's remove all.yaml, it's not necessary to have an artefact that merges all into one

(the longer term vision is that we do indeed have interoperable templates with LLMs dynamically selecting which one to use but for now each template needs to be allowed to be autonomous and have slightly different modeling of the same concept)
