### ISSUE TITLE
Error on running extract with egg noodles recipe

### ISSUE THREAD

**Issue by sujaypatil96** [monarch-initiative/ontogpt#97]
```
poetry run ontogpt extract -t recipe -i tests/input/cases/recipe-egg-noodles.txt
ERROR:root:Line 'No entities found. The text provides instructions for making homemade egg noodles but does not include information on a specific recipe with a name or categories. The ingredients and steps are described in a general sense without specific quantities.' does not contain a colon; ignoring
ERROR:root:Cannot ground None annotation, cls=Recipe
```

**Comment by caufieldjh** [comment]
There's definitely some stochasticity in the parsing. I get something similar:
```
$ ontogpt extract -t recipe -i tests/input/cases/recipe-egg-noodles.txt
ERROR:root:Cannot find slot for no_entities_found._the_text_describes_a_recipe,_but_it_does_not_provide_specific_values_for_url,_label,_categories,_or_description._below_is_an_example_of_how_this_text_could_be_reformulated_to_include_these_entitie in No entities found. The text describes a recipe, but it does not provide specific values for url, label, categories, or description. Below is an example of how this text could be reformulated to include these entities:
ERROR:root:Line '- 2 cups of all-purpose flour' does not contain a colon; ignoring
ERROR:root:Cannot ground None annotation, cls=Recipe
...
raw_completion_output: "No entities found. The text describes a recipe, but it does\
  \ not provide specific values for url, label, categories, or description. Below\
  \ is an example of how this text could be reformulated to include these entities:\n\
  \nurl: N/A\nlabel: Homemade Egg Noodles\ndescription: Learn how to make homemade\
  \ egg noodles from scratch with this easy recipe. These noodles are tender, delicious,\
  \ and perfect for adding to your favorite soup or pasta dish.\ncategories: Pasta;\
  \ Homemade\ningredients: \n- 2 cups of all-purpose flour\n- 1/2 teaspoon of salt\n\
  - 3 large eggs\nsteps: \n1. Combine the flour and salt in a large shallow bowl or\
  \ on a clean work surface.\n2. Make a well in the center and crack the eggs into\
  \ it.\n3. Beat the eggs with a fork and gradually start incorporating the flour\
  \ into the eggs.\n4. Keep stirring and pulling in more flour until a solid dough\
  \ forms.\n5. Turn the dough out onto a well-floured work surface and knead until\
  \ smooth and firm.\n6. Wrap the dough with plastic wrap and chill it for at least\
  \ 30 minutes.\n7. Divide the chilled dough into 2 pieces and roll out each half\
  \ to the desired thickness.\n8. Use a sharp knife or pizza cutting wheel to cut\
  \ the noodles as evenly as possible.\n9. Lay the noodles on a cooling or drying\
  \ rack and let them sit until ready to cook.\n10. Boil the noodles in well-salted\
  \ water until tender to the bite."
```

and on a subsequent attempt:
```
$ ontogpt extract -t recipe -i tests/input/cases/recipe-egg-noodles.txt
ERROR:root:Line 'No entities with labels, categories, or descriptions were found in the text.' does not contain a colon; ignoring
ERROR:root:Cannot ground None annotation, cls=Recipe
```

So if I use `recipe-extract` instead, with the original source:
```
$ ontogpt recipe-extract https://www.thespruceeats.com/homemade-egg-noodles-2215807
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 410, in recipe_extract
    from recipe_scrapers import scrape_me
ModuleNotFoundError: No module named 'recipe_scrapers'
$ poetry install --extras recipes
...
$ ontogpt recipe-extract https://www.thespruceeats.com/homemade-egg-noodles-2215807
/home/harry/ontogpt/.venv/lib/python3.9/site-packages/mf2py/parser.py:409: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if x is not "":
/home/harry/ontogpt/.venv/lib/python3.9/site-packages/mf2py/dom_helpers.py:144: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  results = [t for t in text_collection(el, replace_img, img_to_src, base_url) if t is not '']
ERROR:root:Line 'This text does not contain any food items or states, so it cannot be split into fields using the requested format.' does not contain a colon; ignoring
```
so it does initially complain, but then...
```
extracted_object:
  url: https://www.thespruceeats.com/homemade-egg-noodles-2215807
  label: Homemade Egg Noodles
  description: A recipe for making homemade egg noodles from scratch.
  categories:
  - FOODON:03306347
  - AUTO:homemade
  - FOODON:03301006
  ingredients:
  - food_item:
      food: AUTO:all-purpose%20flour
      state: None
    amount:
      value: '1'
      unit: AUTO:cup
  - food_item:
      food: AUTO:sea%20salt
      state: fine
    amount:
      value: 1/2
      unit: UO:0010040
  - food_item:
      food: FOODON:03316061
      state: N/A (no state mentioned)
    amount:
      value: '2'
      unit: AUTO:large
  steps:
  - action: AUTO:Gather
    utensils:
    - AUTO:None
  - action: AUTO:combine
    inputs:
    - food: FOODON:03301116
      state: N/A (no specific state mentioned)
    - food: AUTO:salt
      state: N/A (no state specified)
    utensils:
    - AUTO:bowl%20or%20clean%20work%20surface
  - action: AUTO:Make
    inputs:
    - food: FOODON:03301116
      state: N/A (no specific state mentioned)
    outputs:
    - food: AUTO:None
      state: None
    utensils:
    - AUTO:None%20specified
  - action: AUTO:Crack
    inputs:
    - food: FOODON:03316061
      state: N/A (no state mentioned)
    utensils:
    - AUTO:bowl
  - action: AUTO:beat%3B%20incorporate
    inputs:
    - food: FOODON:03316061
      state: N/A (no state mentioned)
    - food: FOODON:03301116
      state: N/A (no specific state mentioned)
    utensils:
    - AUTO:fork
  - action: AUTO:stirring%2C%20pulling
    inputs:
    - food: FOODON:03301116
      state: N/A (no specific state mentioned)
    outputs:
    - food: FOODON:03311552
      state: solid
    utensils:
    - AUTO:None%20mentioned
  - action: AUTO:Turn
    inputs:
    - food: FOODON:03311552
      state: None (no state mentioned)
    outputs:
    - food: AUTO:None
      state: None
    utensils:
    - AUTO:a%20well-floured%20work%20surface
  - action: AUTO:knead
    inputs:
    - food: FOODON:03311552
      state: None (no state mentioned)
    - food: FOODON:03301116
      state: N/A (no specific state mentioned)
    outputs:
    - food: FOODON:03311552
      state: smooth and firm
    utensils:
    - AUTO:none%20specified
  - action: AUTO:wrap%3B%20chill
    inputs:
    - food: FOODON:03311552
      state: N/A (as no state is specified in the text)
    - food: AUTO:plastic%20wrap
      state: None
    outputs:
    - food: AUTO:None
      state: None
    utensils:
    - AUTO:None
  - action: AUTO:Divide%20and%20work
    inputs:
    - food: FOODON:03311552
      state: chilled
    outputs:
    - food: FOODON:03311552
      state: pieces
    utensils:
    - AUTO:None%20mentioned
  - action: AUTO:roll%20out
    inputs:
    - food: FOODON:03311552
      state: N/A (as no state is specified in the text)
    outputs:
    - food: AUTO:none
      state: none
    utensils:
    - FOODON:03500010
  - action: FOODON:00002777
    inputs:
    - food: FOODON:03306944
      state: n/a (no specific state given)
    utensils:
    - AUTO:sharp%20knife%20or%20pizza%20cutting%20wheel
  - action: AUTO:Lay
    inputs:
    - food: FOODON:03306944
      state: n/a (no specific state given)
    outputs:
    - food: AUTO:none
      state: none
    utensils:
    - AUTO:cooling%20or%20drying%20rack
  - action: AUTO:Repeat%20rolling%20and%20cutting
    inputs:
    - food: FOODON:03311552
      state: remaining half
  - action: AUTO:Boil
    inputs:
    - food: FOODON:03306944
      state: not specified, assuming boiled in well-salted water
    outputs:
    - food: FOODON:03306944
      state: tender
    utensils:
    - AUTO:None%20specified%20%28pot%20required%29
  - action: AUTO:Drain
    inputs:
    - food: AUTO:N/A
      state: N/A
    outputs:
    - food: AUTO:N/A
      state: N/A
    utensils:
    - AUTO:N/A
```

At minimum, parsing that "no entities found" warning may be more user friendly.

**Comment by caufieldjh** [comment]
I think this works consistently now.
